### PR TITLE
Issue submission

### PR DESCRIPTION
**Pull request by paranoidcake**
Updating the issue submission page to match the design as listed in #4

### CODE REVIEW

**Comment by paranoidcake** [comment]
Currently has merge conflict as login service is imported and injected in master branch, while it is not needed in the component.
I would accept the change of this branch as a result

**Comment by ericm** [comment]
Hopefully that resolves it

**Comment by ericm** [comment]
#fixiversity/tracking#1

**Comment by ericm** [comment]
Since the conflicts were fixed, I'll merge it.

**Pull request merged**
